import { model, Schema } from "mongoose"

const teacherSchema = new Schema({
  nama: { type: String, required: true },
  NUPTK: { type: String, required: true },
  jenis_kelamin: { type: String, enum: ["male", "female"], required: true },
  tempat_lahir: { type: String, required: true },
  tanggal_lahir: { type: Date, required: true },
  NIP: { type: String, default: null },
  status_kepegawaian: { type: String, required: true, enum: ['PNS', 'Guru Honor Sekolah', 'GTY/PTY', 'PPPK'] },
  jenis_PTK: { type: String, default: 'Guru' },
  agama: { type: String, required: true, enum: ['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha'] },
  alamat_jalan: { type: String, required: true },
  RT: { type: Number, required: true },
  RW: { type: Number, required: true },
  dusun: { type: String, required: true },
  desa_kelurahan: { type: String, required: true },
  kecamatan: { type: String, required: true },
  kode_pos: { type: String, default: null },
  telepon: { type: String, default: null },
  email: { type: String, required: true },
  tugas_tambahan: { type: String, default: null },
  SK_CPNS: { type: String, default: null },
  tanggal_CPNS: { type: Date, default: null },
  SK_pengangkatan: { type: String, required: true },
  TMT_pengangkatan: { type: Date, required: true },
  lembaga_pengangkatan: { type: String, required: true },
  pangkat_golongan: { type: String, default: null },
  sumber_gaji: { type: String, required: true },
  nama_ibu_kandung: { type: String, required: true},
  status_pernikahan: { type: String, required: true },
  nama_pasangan: { type: String, default: null },
  NIP_pasangan: { type: String, default: null },
  pekerjaan_pasangan: { type: String, required: true },
  TMT_PNS: { type: Date, required: true },
  sudah_lisensi_kepala_sekolah: { type: Boolean, required: true },
  pernah_diklat_kepengawasan: { type: Boolean, required: true },
  keahlian_braille: { type: Boolean, required: true },
  keahlian_bahasa_isyarat: { type: Boolean, required: true },
  NPWP: { type: String, default: null },
  nama_wajib_pajak: { type: String, default: null },
  kewarganegaraan: { type: String, default: 'ID' },
  bank: { type: String, default: null },
  no_rekening: { type: String, default: null },
  rekening_atas_nama: { type: String, default: null },
  NIK: { type: String, required: true },
  no_KK: { type: String, default: null },
  karpeg: { type: String, default: null },
  karis_karsu: { type: String, default: null },
  lintang: { type: String, default: null },
  bujur: { type: String, default: null }, 
  NUKS: { type: Boolean, default: null },
})

export const Teacher = model("teachers", teacherSchema)
